import { useState, useCallback } from 'react';
import { supabase } from '@/lib/supabase/client';
import type { Message, ChatSummary } from '@/types';

// Demo mode check
const isDemoMode = !import.meta.env.VITE_SUPABASE_URL;

// Gemini API integration through Supabase Edge Function
const GEMINI_API_URL = (import.meta.env.VITE_SUPABASE_FUNCTIONS_URL || '') + '/gemini-ai';

export function useAI() {
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [isTranslating, setIsTranslating] = useState(false);
  const [isTranscribing, setIsTranscribing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Summarize conversation using Gemini
  const summarizeConversation = useCallback(async (
    messages: Message[],
    language: string = 'en'
  ): Promise<ChatSummary | null> => {
    if (messages.length === 0) return null;

    // Demo mode - return mock summary
    if (isDemoMode) {
      return {
        summary: [
          'Jane asked how John was doing and they discussed the new AI-powered chat app project.',
          'John shared details about Stunner, featuring real-time messaging, voice notes, and smart AI summaries.',
          'Jane complimented the sleek dark theme design and expressed excitement about the app.',
        ],
        generated_at: new Date().toISOString(),
      };
    }

    setIsSummarizing(true);
    setError(null);

    try {
      // Get last 20 messages
      const recentMessages = messages
        .slice(-20)
        .map(m => ({
          sender: m.sender?.full_name || m.sender?.username || 'Unknown',
          content: m.content,
          timestamp: m.created_at,
        }));

      const session = await supabase.auth.getSession();
      const response = await fetch(GEMINI_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.data.session?.access_token}`,
        },
        body: JSON.stringify({
          action: 'summarize',
          messages: recentMessages,
          language,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to summarize conversation');
      }

      const data = await response.json();
      return {
        summary: data.summary,
        generated_at: new Date().toISOString(),
      };
    } catch (err) {
      console.error('Error summarizing conversation:', err);
      setError('Failed to summarize conversation');
      return null;
    } finally {
      setIsSummarizing(false);
    }
  }, []);

  // Translate message using Gemini
  const translateMessage = useCallback(async (
    text: string,
    targetLanguage: string,
    sourceLanguage?: string
  ): Promise<string | null> => {
    if (!text) return null;

    // Demo mode - return mock translation
    if (isDemoMode) {
      // Just return the original text with a note for demo
      return `[Translated] ${text}`;
    }

    setIsTranslating(true);
    setError(null);

    try {
      const session = await supabase.auth.getSession();
      const response = await fetch(GEMINI_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.data.session?.access_token}`,
        },
        body: JSON.stringify({
          action: 'translate',
          text,
          targetLanguage,
          sourceLanguage,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to translate message');
      }

      const data = await response.json();
      return data.translatedText;
    } catch (err) {
      console.error('Error translating message:', err);
      setError('Failed to translate message');
      return null;
    } finally {
      setIsTranslating(false);
    }
  }, []);

  // Transcribe voice note using Gemini
  const transcribeVoice = useCallback(async (
    audioUrl: string,
    language: string = 'en'
  ): Promise<string | null> => {
    if (!audioUrl) return null;

    // Demo mode - return mock transcription
    if (isDemoMode) {
      return 'This is a demo transcription of the voice note. In production, this would be generated by Gemini AI.';
    }

    setIsTranscribing(true);
    setError(null);

    try {
      const session = await supabase.auth.getSession();
      const response = await fetch(GEMINI_API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.data.session?.access_token}`,
        },
        body: JSON.stringify({
          action: 'transcribe',
          audioUrl,
          language,
        }),
      });

      if (!response.ok) {
        throw new Error('Failed to transcribe voice note');
      }

      const data = await response.json();
      return data.transcription;
    } catch (err) {
      console.error('Error transcribing voice:', err);
      setError('Failed to transcribe voice note');
      return null;
    } finally {
      setIsTranscribing(false);
    }
  }, []);

  return {
    isSummarizing,
    isTranslating,
    isTranscribing,
    error,
    summarizeConversation,
    translateMessage,
    transcribeVoice,
  };
}
